on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: borales/actions-yarn@master
        with:
          args: install
      - name: Test
        uses: borales/actions-yarn@master
        env:
          CI: 'true'
        with:
          args: test --coverage
